// Microsoft Visual C++ generated resource script.
//

#define    IDS_ABOUTBOX            "Version LJV_DllSampleAll(&A)..."
#define    IDS_RESULT_LOG_FORMAT   "_T(""[{0}]:{1}(0x{2:x4}"")"
#define    IDS_RESULT_OK           "OK"
#define    IDS_RESULT_NG           "NG"
#define    IDS_SCMD_INITIALIZE     "Initialize"
#define    IDS_SCMD_GETVERSION     "GetVersion"
#define    IDS_SCMD_FINALIZE       "Finalize"
#define    IDS_SCMD_USBOPEN        "USBOpen"
#define    IDS_SCMD_EHTERNETOPEN   "EthernetOpen"
#define    IDS_SCMD_COMMCLOSE      "CommClose"
#define    IDS_SCMD_REBOOTCONTROLLER "RebootController"

#define    IDS_SCMD_RETURNTOFACTORYSETTING "ReturnToFactorySetting"
#define    IDS_SCMD_GETERROR       "GetError"
#define    IDS_SCMD_CLEARERROR     "ClearError"
#define    IDS_SCMD_TRIGGER        "Trigger"
#define    IDS_SCMD_STARTMEASURE   "StartMeasure"
#define    IDS_SCMD_STOPMEASURE    "StopMeasure"
#define   IDS_SCMD_AUTOZERO       "AutoZero"
#define    IDS_SCMD_TIMING         "Timing"
#define    IDS_SCMD_RESET          "Reset"
#define    IDS_SCMD_CLEARMEMORY    "ClearMemory"
#define    IDS_SCMD_SETSETTING     "SetSetting"
#define    IDS_SCMD_GETSETTING     "GetSetting"
#define    IDS_SCMD_INITIALIZESETTING "InitializeSetting"
#define    IDS_SCMD_REFLECTSETTING "ReflectSetting"
#define    IDS_SCMD_REWRITETEMPORARYSETTING "RewriteTemporarySetting"
#define    IDS_SCMD_CHECKMEMORYACCESS "CheckMemoryAccess"

#define    IDS_SCMD_SETTIME        "SetTime"
#define    IDS_SCMD_GETTIME        "GetTime"
#define    IDS_SCMD_CHANGEACTIVEPROGRAM "ChangeActiveProgram"
#define    IDS_SCMD_GETACTIVEPROGRAM "GetActiveProgram"
#define    IDS_SCMD_GETMEASUREMENTVALUE "GetMeasurementValue"
#define    IDS_SCMD_GETPROFILE     "GetProfile"
#define    IDS_SCMD_GETBATCHPROFILE "GetBatchProfile"
#define    IDS_SCMD_GETPROFILEADVANCE "GetProfileAdvance"
#define    IDS_SCMD_GETBATCHPROFILEADVANCE "GetBatchProfileAdvance"
#define    IDS_SCMD_STARTSTORAGE   "StartStorage"
#define    IDS_SCMD_STOPSTORAGE    "StopStorage"
#define    IDS_SCMD_GETSTORAGESTATUS "GetStorageStatus"
#define    IDS_SCMD_GETSTORAGEDATA "GetStorageData"
#define    IDS_SCMD_GETSTORAGEPROFILE "GetStorageProfile"
#define    IDS_SCMD_GETSTORAGEBATCHPROFILE "GetStorageBatchProfile"
#define    IDS_SCMD_HIGHSPEEDDATAUSBCOMMUNICATIONINITALIZE "HighSpeedDataUSBCommunicationInitalize"
#define    IDS_SCMD_HIGHSPEEDDATAETHERNETCOMMUNICATIONINITALIZE "HighSpeedDataEthernetCommunicationInitalize"
#define    IDS_SCMD_PRESTARTHIGHSPEEDDATACOMMUNICATION "PreStartHighSpeedDataCommunication"
#define    IDS_SCMD_STARTHIGHSPEEDDATACOMMUNICATION "StartHighSpeedDataCommunication"
#define    IDS_SCMD_STOPHIGHSPEEDDATACOMMUNICATION "StopHighSpeedDataCommunication"
#define    IDS_SCMD_HIGHSPEEDDATACOMMUNICATIONFINALIZE "HighSpeedDataCommunicationFinalize"
#define    IDS_RC_FORMAT           "\t->"
#define    IDS_RC_OK               "Normal termination"
#define    IDS_RC_ERR_OPEN_DEVICE  "Failed to open the device"
#define    IDS_RC_ERR_NO_DEVICE    "Device not open"
#define    IDS_RC_ERR_SEND         "Command send error"
#define    IDS_RC_ERR_RECEIVE      "Response reception error"
#define    IDS_RC_ERR_TIMEOUT      "Time out"
#define    IDS_RC_ERR_PARAMETER    "Parameter error"
#define    IDS_RC_ERR_NOMEMORY     "No free space"
#define    IDS_NOT_DEFINE_FORMAT   "#Undefined RC (0x%04X)\r\n"


